name: Deploy Extension

on: 
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of deployment'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install VSCE (Publishing Tool)
        run: npm install -g @vscode/vsce

      - name: Install Dependencies
        working-directory: ./ece2035
        run: npm install

      - name: Build Extension
        working-directory: ./ece2035
        run: npm run compile

      - name: Publish Extension
        working-directory: ./ece2035
        run: vsce publish ${{ github.event.inputs.type }} -p ${{ secrets.AZURE_ACCESS_KEY }}
      
      - name: Commit New Version in package.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version"
        
